### ISSUE TITLE
requires password on channel ?

### ISSUE THREAD

**Issue by calvinz360** [hklcf/myTV-SUPER-Player#1]
Selecting any channels on the application would prompt a password ?

**Comment by hklcf** [comment]
Yes, you must input a password on this version.

BTW, the streaming source blocked by mytv already, im working on it.

**Comment by calvinz360** [comment]
thanks for notifying :) I've gotten valueable API information from you and made a similar powershell based solution (only mytv), if you don't mind we could work together on this and share our findings ?

**Comment by whyhung** [comment]
Brother hklcf,

I am looking forward for your update, as I am facing the same issue of blocked streaming source.. Keep it up, wait for your good news..

Best Regards,
whyhung

**Comment by hklcf** [comment]
@calvinz360 ur welcome, please take a look at [https://github.com/hklcf/myTV-api/commit/c687d4c32fb85233f98ef17109d900222ce5696b]

**Comment by hklcf** [comment]
updated to v1.2

**Comment by whyhung** [comment]
would like to ask for favorite for the password for the player.
could send to my email please.  zhouyu0326@gmail.com
Many Thanks

**Comment by hklcf** [comment]
@whyhung do not need any password on this version.

**Comment by whyhung** [comment]
Thanks hklcf,  I just saw you have updated the run.exe as well.  Thank you
very much for your sharing in advance.. ^^"

**Comment by 556556bt** [comment]
how to switch audio channel and subtitle?

**Comment by hklcf** [comment]
@556556bt to switch audio, simple press "A" on your keyboard.
doesn't support subtitle at this moment

**Comment by whyhung** [comment]
Might I know if it possible to record?  Kindly wait for your reply, thanks

**Comment by 556556bt** [comment]
that's great. btw, I found it won't support hw decode and draw cpu in very high usage.

**Comment by hklcf** [comment]
@whyhung Yes...:speak_no_evil::speak_no_evil::speak_no_evil:

**Comment by whyhung** [comment]
might I know which key to press to record?  Many thanks ^^"
